
data:
  raw_dir: "./data/raw" 
  processed_dir: "./data/processed"
  sample_rate: 8000
  batch_size: 256
  version: "v0.1"

model_type: "cnn_fp32"

model:
  base_cnn:
    n_input: 1
    n_output: 35
    stride: 16
    n_channel: 32
    conv_kernel_sizes: [80, 3, 3, 3]
    version: "demo"

train:
  lr: 0.001
  weight_decay: 0.0001
  step_size: 10
  gamma: 0.1
  log_interval: 100
  n_epoch: 20
  seed: 42
  version: "demo"