data:
  raw_dir: "./data/raw"
  processed_dir: "./data/processed" 
  sample_rate: 8000
  batch_size: 256
  version: "v0.1"

model_type: "cnn_ptq"

model:
  base_cnn:
    n_input: 1
    n_output: 35
    stride: 16
    n_channel: 32
    conv_kernel_sizes: [80, 3, 3, 3]
    pretrained_path: "./models/cnn_fp32_model.pth"
    version: "demo"
